ProyectoCrud.AppWeb/Models/ErrorViewModel.cs
namespace ProyectoCrud.AppWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoCrud.AppWeb/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoCrud.DAL.Interface;
using ProyectoCrud.DAL.Models;

namespace ProyectoCrud.AppWeb.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAuth _authInz;
        public AccountController(IAuth authInz)
        {
            _authInz = authInz;
        }
        public IActionResult Index()
        {
            List<AppUser> users = this._authInz.GetUsers();
            return View(users);
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(Accseso request) 
        {
            if (!ModelState.IsValid)

                return View(request);  
            var result = await _authInz.login(request);
            if (result.StatusCode == 1)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(Login));
            }
        }
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Registration(RegisterRequest request)
        {
            if (!ModelState.IsValid) { return View(request); }

            var result = await this._authInz.Register(request);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }

        [Authorize]
        public async Task<IActionResult> logout()
        {
            await this._authInz.logout();
            return RedirectToAction(nameof(Login));
        }
        [HttpGet]
        public ViewResult SoftDelete(AppUser user)
        {
            return View(user);
        }

        public IActionResult resetPass()
        {
            return View();
        }
        [HttpPost("change-password")]
        public async Task<ActionResult> resetPass(ResetPasswordRequest model)
        {
            if (ModelState.IsValid)
            {
                var result = await _authInz.ResetPassword(model);
                if (result.Succeeded)
                {
                    ViewBag.IsSuccess = true;
                    ModelState.Clear();
                    return View();
                }
                foreach (var erro in result.Errors)
                {
                    ModelState.AddModelError("", erro.Description);
                }
            }
            return View();
        }


    }
}

ProyectoCrud.AppWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Globalization;

namespace ProyectoCrud.AppWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProyectoCrud.AppWeb/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoCrud.BL.Interface;
using MU = ProyectoCrud.DAL.Models;

namespace ProyectoCrud.AppWeb.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioBL usuarioBL;
        public UsuarioController(IUsuarioBL usuarioBL)
        {
            this.usuarioBL = usuarioBL;
        }
        public async Task<IActionResult> Index()
        {
            List<MU::Usuario> usuarios = await this.usuarioBL.GetUsuarios();
            return View(usuarios);
        }
        public IActionResult Crear()
        {
            return View(new MU.Usuario());
        }

        public async Task<IActionResult> Edit(string id)
        {
            MU::Usuario usuarios = await this.usuarioBL.GetUsuariosbyid(Convert.ToInt32(id));
            return View("Crear", usuarios);
        }
        public async Task<IActionResult> Guardar(MU::Usuario usuario)
        {
            string Response = await this.usuarioBL.Guardar(usuario);
            return Json(Response);
        }
        public async Task<IActionResult> EliminarUsuario(string id)
        {
            string Response = await this.usuarioBL.Eliminar(Convert.ToInt32(id));
            return Json(Response);
        }

    }
}

ProyectoCrud.AppWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoCrud.AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoCrud.AppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoCrud.AppWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">CRUD ASP.NET CORE 6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Usuario" asp-action="Index">Tabla</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Index">Usuario Registrado</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProyectoCrud.AppWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoCrud.AppWeb/Views/Usuario/Crear.cshtml
@{
    ViewData["Title"] = "Crear";
}

@model ProyectoCrud.DAL.Models.Usuario;


<div class="card">
    <div class="card-title">
        <h1>Crear</h1>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Id</label>
                    <input id="txtid" value="@Model.Id"  disabled="disabled" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Nombre</label>
                    <input id="txtnombre" value="@Model.Nombre"  class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Edad</label>
                    <input id="txtedad" value="@Model.Edad" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Email</label>
                    <input id="txtemail" value="@Model.Email" class="form-control" />
                </div>
            </div>
        </div>
         <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Salario</label>
                    <input id="txtsalario" value="@Model.Salario" class="form-control" />
                </div>
            </div>
        </div>
         <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label>Fecha</label>
                    <input id="txtfecha" value="@Model.Fecha" type="date" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group" style="margin-top:10px">
                   <a onclick="handlesave()" class="btn btn-success">Guardar</a> <a onclick="backtolist()" class="btn btn-danger">Cancelar</a>
                </div>
            </div>
        </div>

    </div>
</div>

<script type="text/javascript">

    function backtolist()
    {
        window.location.href = "/Usuario/Index";
    }
    function handlesave() {
        var Id = $('#txtid').val();
        var nombre = $('#txtnombre').val();
        var edad = $('#txtedad').val();
        var email = $('#txtemail').val();
        var salario = $('#txtsalario').val();
        var fecha = $('#txtfecha').val();

        var proceso = true;


        //validacion 
        if (nombre != '' && nombre != null) {
            $('#txtnombre').css('border-color', '#ccc');
        }else{
            $('#txtnombre').css('border-color', 'red');
            proceso=false;
        }
        if (salario != '' && salario != null) {
            $('#txtsalario').css('border-color', '#ccc');
        }else{
            $('#txtsalario').css('border-color', 'red');
            proceso = false;
        }
        if(proceso)
        {
            var _usuario = new Object();
            _usuario.Id=parseInt(Id);
            _usuario.Nombre = nombre;
            _usuario.Edad = parseInt(edad);
            _usuario.Email = email;
            _usuario.Salario = parseFloat(salario);
            _usuario.Fecha = fecha;

            $.ajax({
                type:"POST",
                url: "/usuario/Guardar",
                data: _usuario,
                success: function(data) {
                    if (data == 'pass') {
                        alert('Usuario Guardado.')
                        backtolist();
                    }else{
                        alert('el proceso fallo :' + data)
                    }
                },
                failure: function(err) {

                }
            });
        }
    }

</script>

ProyectoCrud.AppWeb/Views/Usuario/Index.cshtml
@model List<ProyectoCrud.DAL.Models.Usuario>


 
    <div class="card">
        <div class="card-body">
        <a class="btn btn-success" asp-controller="Usuario" asp-action="Crear">Agregar</a>
            <div class="card-title">
            <h2>Lista de Usuarios</h2>
            </div>
        <table class="table table-bordered table-striped" id="tblist">
                <thead class="bg-dark text-white"> 
                    <tr>
                        <td>Id</td>
                        <td>Nombre</td>
                        <td>Edad</td>
                        <td>Email</td>
                        <td>Salario</td>
                        <td>Fecha</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                @foreach(ProyectoCrud.DAL.Models.Usuario item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(itemdisplay=>item.Id)
                            @Html.HiddenFor(itemdisplay=>item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(itemdisplay=>item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(itemdisplay=>item.Edad)
                        </td>
                        <td>
                            @Html.DisplayFor(itemdisplay=>item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(itemdisplay=>item.Salario)
                        </td>
                        <td>
                            @Html.DisplayFor(itemdisplay=>item.Fecha)
                        </td>
                        <td>
                            <a onclick="Edit(this)" class="btn btn-primary">Editar</a> |
                            <a onclick="Eliminar(this)" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>

    <script type="text/javascript">

        var js = jQuery.noConflict(true);
        js(document).ready(function()
        {
            LoadListing()
            js('#tblist').DataTable({

            });
        });
        
       function Edit(element){
            var id=$(element).closest('tr').find('input[type=hidden]').val();
             window.location.href = "/Usuario/Edit?Id="+id;
        }

    function Eliminar(element) {
        var id = $(element).closest('tr').find('input[type=hidden]').val();
        if(confirm("Seguro que quieres eliminar?")){
            $.ajax({
                type: "POST",
                url: "/Usuario/EliminarUsuario",
                data: {Id: id},
                success: function (data) {
                    if (data == 'pass') {
                        alert('Usuario Eliminado.')
                        window.location.reload();
                    } else {
                        alert('el proceso fallo :' + data)
                    }
                },
                failure: function (err) {

                }
            });
        }
        //window.location.href = "/Usuario/Edit?Id=" + Id;
    }
    //function LoadListing()
    //{
    //    var empdata=[];
    //    $.ajax({
    //        type: "POST",
    //        url: "/Usuario/GetAll",
    //        async: false,
    //        success: function (data) {
    //           $.each(data, function(key, value)
    //           {
    //                var editbtn="<a onclick='Edit(this)' class='btn btn-primary'>Editar</a>";
    //                var deletetbtn="<a onclick='Eliminar(this)' class='btn btn-danger'>Eliminar</a>";
    //                var hidden= "<input type='hidden' value" + value.id + "/>";
    //                var action = editbtn + " | " + deletetbtn + hidden;
    //                empdata.push([value.id, value.nombre,
    //                value.edad, value.email, value.salario, 
    //                value.fecha,action])
    //           })
    //        },
    //        failure: function (err) {

    //        }
    //    });
    //    js('#tblist').DataTable({
    //        data: empdata
    //    });
    //}

    </script>